# Small Room Heater
- platform: generic_thermostat
  unique_id: smallroom_heater
  name: SmallRoom Heater
  heater: switch.smallroom_heater_tmp
  ac_mode: false
  min_temp: 10
  max_temp: 30
  hot_tolerance: 0.5
  cold_tolerance: 0.5
  target_temp: 24
  away_temp: 2
  target_sensor: sensor.smallroom_temperature
