# SmallRoom Heater
- platform: ELKO_telnet
  switches:
    smallroom_heater:
      resource: "192.168.88.246"
      port: 1111
      command_on: "1"
      command_off: "0"
      value_template: >-
        {% if value == '1' %}
          True
        {% else %}
          False
        {% endif %}
      timeout: 0.1
      name: SmallRoom Heater
      device_id: "0x01020004"
# Templates
# SmallRoom Heater Template
- platform: template
  switches:
    smallroom_heater_tmp:
      value_template: "{{ is_state('switch.smallroom_heater', 'on') }}"
      turn_on:
        service: switch.turn_on
        target:
          entity_id: switch.smallroom_heater
      turn_off:
        service: switch.turn_off
        target:
          entity_id: switch.smallroom_heater
      icon_template: >-
        {% if is_state('switch.smallroom_heater', 'on') %}
          mdi:radiator
        {% else %}
          mdi:radiator-disabled
        {% endif %}