# SmallRoom Heater
- platform: ELKO_telnet
  switches:
    smallroom_heater: &settings
      resource: "192.168.88.246"
      port: 1111
      command_on: "0"
      command_off: "1"
      value_template: >-
        {% if value == '1' %}
          True
        {% else %}
          False
        {% endif %}
      timeout: 0.1
      name: SmallRoom Heater
      device_id: "0x01020004"
- platform: ELKO_telnet
  switches:
    smallroom_curtains_open:
      <<: *settings
      name: Smallroom Curtains Open
      device_id: "0x0102006e"
- platform: ELKO_telnet
  switches:
    smallroom_curtains_close:
      <<: *settings
      name: Smallroom Curtains Close
      device_id: "0x0102006f"
- platform: ELKO_telnet
  switches:
    smallroom_tule_open:
      <<: *settings
      name: Smallroom Tule Open
      device_id: "0x01020071"
- platform: ELKO_telnet
  switches:
    smallroom_tule_close:
      <<: *settings
      name: Smallroom Tule Close
      device_id: "0x01020070"

# Templates
# SmallRoom Heater Template
- platform: template
  switches:
    smallroom_heater_tmp:
      value_template: "{{ is_state('switch.smallroom_heater', 'on') }}"
      turn_on:
        service: switch.turn_on
        target:
          entity_id: switch.smallroom_heater
      turn_off:
        service: switch.turn_off
        target:
          entity_id: switch.smallroom_heater
      icon_template: >-
        {% if is_state('switch.smallroom_heater', 'on') %}
          mdi:radiator
        {% else %}
          mdi:radiator-disabled
        {% endif %}