- id: cabinet_light_table
  alias: Cabinet Light Table
  description: ''
  trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id:
    - sensor.cabinet_light_table
  condition: []
  action:
  - condition: template
    value_template: "{{ states('switch.cabinet_light_table_tmp') != states('sensor.cabinet_light_table') }}"
  - service: switch.turn_{{states('sensor.cabinet_light_table')}}
    data: {}
    target:
      entity_id: switch.cabinet_light_table_tmp
  mode: single
- id: cabinet_light_wall
  alias: Cabinet Light Wall
  description: ''
  trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id:
    - sensor.cabinet_light_wall
  condition: []
  action:
  - condition: template
    value_template: "{{ states('switch.cabinet_light_wall_tmp') != states('sensor.cabinet_light_wall') }}"
  - service: switch.turn_{{states('sensor.cabinet_light_wall')}}
    data: {}
    target:
      entity_id: switch.cabinet_light_wall_tmp
  mode: single
- id: cabinet_chandelier
  alias: Cabinet Chandelier
  description: ''
  trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id:
    - sensor.cabinet_chandelier
  condition: []
  action:
  - condition: template
    value_template: "{{ states('switch.cabinet_chandelier_tmp') != states('sensor.cabinet_chandelier') }}"
  - service: switch.turn_{{states('sensor.cabinet_chandelier')}}
    data: {}
    target:
      entity_id: switch.cabinet_chandelier_tmp
  mode: single
- id: cabinet_curtain
  alias: Cabinet Curtains
  description: ''
  trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id:
    - sensor.cabinet_curtains_open
  condition: []
  action:
  - condition: template
    value_template: "{{ states('cover.cabinet_curtain') != states('sensor.cabinet_curtains_open') }}"
  - service: cover.{{ states('sensor.cabinet_curtains_open') | replace("closed", "close") }}_cover
    data: {}
    target:
      entity_id: cover.cabinet_curtain
  mode: single
- id: 'cabinet_switch_1_up_1'
  alias: Cabinet Switch 1 Up 1
  description: 'Kitchen Switch 1 Up 1'
  trigger:
  - platform: webhook
    webhook_id: '0x01010039'
  - platform: webhook
    webhook_id: '0x01010004'
  condition:
  - condition: template
    value_template: "{{ trigger.json.event_id == '29' and trigger.json.device_state == '1' }}"
  action:
  - choose:
    - conditions:
      - condition: template
        value_template: "{{ is_state('switch.cabinet_light_wall', 'off') }}"
      sequence:
      - service: switch.turn_on
        data: {}
        target:
          entity_id: switch.cabinet_light_wall
      - service: switch.turn_on
        data: {}
        target:
          entity_id: switch.cabinet_switch_1_green_1
    - conditions:
      - condition: template
        value_template: "{{ is_state('switch.cabinet_light_wall', 'on') }}"
      sequence:
      - service: switch.turn_off
        data: {}
        target:
          entity_id: switch.cabinet_light_wall
      - service: switch.turn_off
        data: {}
        target:
          entity_id: switch.cabinet_switch_1_green_1
- id: 'cabinet_camera'
  alias: Cabinet Camera
  description: 'Kitchen Camera'
  trigger:
  - platform: webhook
    webhook_id: '0x01010004'
  condition:
  - condition: template
    value_template: "{{ trigger.json.event_id == '29' and trigger.json.device_state == '1' }}"
  action:
  - choose:
    - conditions:
      - condition: template
        value_template: "{{ is_state('switch.cabinet_light_wall', 'off') }}"
      sequence:
      - service: switch.turn_on
        data: {}
        target:
          entity_id: switch.cabinet_light_wall
      - service: switch.turn_on
        data: {}
        target:
          entity_id: switch.cabinet_switch_1_green_1