- platform: command_line
  unique_id: hall_temperature
  name: Hall Temperature
  command: "python3 custom_components/ELKO_Telnet/get_data.py"
  unit_of_measurement: "°C"
  value_template: "{{ value | multiply(0.001) | round(1) }}"