# General Listener
- platform: command_line
  unique_id: event_listener
  name: Event Listener
  command: "python3 custom_components/ELKO_telnet/if_run.py"
  value_template: ""
- platform: command_line
  unique_id: cabinet_temperature
  name: Cabinet Temperature
  command: "python3 custom_components/ELKO_telnet/get_data.py -h 192.168.88.246 -p 1111 -i 0x01050017"
  unit_of_measurement: "°C"
  value_template: "{{ value | multiply(0.01) | round(1) }}"
- platform: command_line
  unique_id: cabinet_light_table
  name: Cabinet Light Table
  command: "python3 custom_components/ELKO_telnet/get_data.py -h 192.168.88.246 -p 1111 -i 0x01020029"
  value_template: >-
    {% if value == '1' %}
      on
    {% else %}
      off
    {% endif %}
- platform: command_line
  unique_id: cabinet_light_wall
  name: Cabinet Light Wall
  command: "python3 custom_components/ELKO_telnet/get_data.py -h 192.168.88.246 -p 1111 -i 0x01020011"
  value_template: >-
    {% if value == '1' %}
      on
    {% else %}
      off
    {% endif %}
- platform: command_line
  unique_id: cabinet_chandelier
  name: Cabinet Chandelier
  command: "python3 custom_components/ELKO_telnet/get_data.py -h 192.168.88.246 -p 1111 -i 0x01020039"
  value_template: >-
    {% if value == '1' %}
      on
    {% else %}
      off
    {% endif %}
- platform: command_line
  unique_id: cabinet_curtains_open
  name: Cabinet Curtains Open
  command: "python3 custom_components/ELKO_telnet/get_data.py -h 192.168.88.246 -p 1111 -i 0x0102002f"
  value_template: >-
    {% if value == '1' %}
      open
    {% else %}
      closed
    {% endif %}
- platform: command_line
  unique_id: cabinet_curtains_close
  name: Cabinet Curtains Close
  command: "python3 custom_components/ELKO_telnet/get_data.py -h 192.168.88.246 -p 1111 -i 0x01020026"
  value_template: >-
    {% if value == '1' %}
      closed
    {% else %}
      open
    {% endif %}


- platform: ELKO_telnet
  sensors:
    cabinet_temperature_test:
      friendly_name: "Cabinet Temperature Test"
      host: "192.168.88.246"
      device_id: "0x01050017"
      port: 1111
      device_class: 'temperature'
      unit_of_measurement: "°C"
- platform: ELKO_telnet
  sensors:
    cabinet_curtains_open_test:
      friendly_name: "Cabinet Curtains Open Test"
      host: "192.168.88.246"
      device_id: "0x0102002f"
      port: 1111
      device_class: 'binary'
      unit_of_measurement: "open/closed"
- platform: ELKO_telnet
  sensors:
    cabinet_curtains_closed_test:
      friendly_name: "Cabinet Curtains Closed Test"
      host: "192.168.88.246"
      device_id: "0x01020026"
      port: 1111
      device_class: 'binary'
      unit_of_measurement: "closed/open"
- platform: ELKO_telnet
  sensors:
    cabinet_backlight_wall_test:
      friendly_name: "Cabinet Backlight Wall Test"
      host: "192.168.88.246"
      device_id: "0x01020011"
      port: 1111
      device_class: 'binary'
      unit_of_measurement: "on/off"
- platform: ELKO_telnet
  sensors:
    cabinet_backlight_wall_test_reverse:
      friendly_name: "Cabinet Backlight Wall Test Reverse"
      host: "192.168.88.246"
      device_id: "0x01020011"
      port: 1111
      device_class: 'binary'
      unit_of_measurement: "off/on"