# General Listener
- platform: command_line
  unique_id: event_listener
  name: Event Listener
  command: "python3 custom_components/ELKO_telnet/if_run.py"
  value_template: ""
- platform: ELKO_telnet
  sensors:
    cabinet_temperature: &sensors
      friendly_name: "Cabinet Temperature"
      host: "192.168.88.246"
      device_id: "0x01050017"
      port: 1111
      device_class: 'temperature'
      unit_of_measurement: "°C"
- platform: ELKO_telnet
  sensors:
    cabinet_light_table:
      <<: *sensors
      friendly_name: "Cabinet Backlight Table"
      device_id: "0x01020029"
      device_class: 'binary'
      unit_of_measurement: "on/off"
- platform: ELKO_telnet
  sensors:
    cabinet_light_wall:
      <<: *sensors
      friendly_name: "Cabinet Backlight Wall"
      device_id: "0x01020011"
      device_class: 'binary'
      unit_of_measurement: "on/off"
- platform: ELKO_telnet
  sensors:
    cabinet_chandelier:
      <<: *sensors
      friendly_name: "Cabinet Chandelier"
      device_id: "0x01020039"
      device_class: 'binary'
      unit_of_measurement: "on/off"
- platform: ELKO_telnet
  sensors:
    cabinet_curtains_open:
      <<: *sensors
      friendly_name: "Cabinet Curtains Open"
      device_id: "0x0102002f"
      device_class: 'binary'
      unit_of_measurement: "open/closed"
- platform: ELKO_telnet
  sensors:
    cabinet_curtains_close:
      <<: *sensors
      friendly_name: "Cabinet Curtains Close"
      device_id: "0x01020026"
      device_class: 'binary'
      unit_of_measurement: "closed/open"