# General Listener
- platform: command_line
  unique_id: event_listener
  name: Event Listener
  command: "custom_components/ELKO_telnet/run_script.sh"
  value_template: ""
- platform: command_line
  unique_id: cabinet_temperature
  name: Cabinet Temperature
  command: "python3 custom_components/ELKO_telnet/get_data.py -h 192.168.88.246 -p 1111 -i 0x01050017"
  unit_of_measurement: "°C"
  value_template: "{{ value | multiply(0.01) | round(1) }}"
