
- platform: ELKO_telnet
  switches:
    cabinet_light_table: &settings
      name: Cabinet Light Table
      resource: "192.168.88.246"
      device_id: "0x01020029"
      port: 1111
      command_on: "1"
      command_off: "0"
      value_template: >-
        {% if value == '1' %}
          True
        {% else %}
          False
        {% endif %}
      timeout: 0.1
- platform: ELKO_telnet
  switches:
    cabinet_light_wall:
      <<: *settings
      name: Cabinet Light Wall
      device_id: "0x01020011"
- platform: ELKO_telnet
  switches:
    cabinet_chandelier:
      <<: *settings
      name: Cabinet Chandelier
      device_id: "0x01020039"
- platform: ELKO_telnet
  switches:
    cabinet_curtains_open:
      <<: *settings
      name: Cabinet Curtains Open
      device_id: "0x0102002f"
- platform: ELKO_telnet
  switches:
    cabinet_curtains_close:
      <<: *settings
      name: Cabinet Curtains Close
      device_id: "0x01020026"
- platform: ELKO_telnet
  switches:
    hall_floor_heater:
      <<: *settings
      name: Hall Floor Heater
      device_id: "0x0102003B"

- platform: template
  switches:
    cabinet_light_table_tmp:
      value_template: "{{ is_state('switch.cabinet_light_table', 'on') }}"
      turn_on:
        service: switch.turn_on
        target:
          entity_id: switch.cabinet_light_table
      turn_off:
        service: switch.turn_off
        target:
          entity_id: switch.cabinet_light_table
      icon_template: >-
        {% if is_state('switch.cabinet_light_table', 'on') %}
          mdi:desk-lamp-on
        {% else %}
          mdi:desk-lamp-off
        {% endif %}

- platform: template
  switches:
    cabinet_light_wall_tmp:
      value_template: "{{ is_state('switch.cabinet_light_wall', 'on') }}"
      turn_on:
        service: switch.turn_on
        target:
          entity_id: switch.cabinet_light_wall
      turn_off:
        service: switch.turn_off
        target:
          entity_id: switch.cabinet_light_wall
      icon_template: >-
        {% if is_state('switch.cabinet_light_wall', 'on') %}
          mdi:wall-sconce-flat
        {% else %}
          mdi:wall-sconce-flat-outline
        {% endif %}

- platform: template
  switches:
    cabinet_chandelier_tmp:
      value_template: "{{ is_state('switch.cabinet_chandelier', 'on') }}"
      turn_on:
        service: switch.turn_on
        target:
          entity_id: switch.cabinet_chandelier
      turn_off:
        service: switch.turn_off
        target:
          entity_id: switch.cabinet_chandelier
      icon_template: >-
        {% if is_state('switch.cabinet_chandelier', 'on') %}
          mdi:ceiling-light
        {% else %}
          mdi:ceiling-light-outline
        {% endif %}