
- platform: ELKO_telnet
  switches:
    cabinet_light_table: &settings
      name: Cabinet Light Table
      resource: "192.168.88.246"
      device_id: "0x01020029"
      port: 1111
      command_on: "1"
      command_off: "0"
      value_template: >-
        {% if value == '1' %}
          True
        {% else %}
          False
        {% endif %}
      timeout: 0.1
- platform: ELKO_telnet
  switches:
    cabinet_switch_1_green_1:
      <<: *settings
      name: Cabinet Switch 1 Green 1
      device_id: "0x01020048"
- platform: ELKO_telnet
  switches:
    cabinet_switch_1_green_2:
      <<: *settings
      name: Cabinet Switch 1 Green 2
      device_id: "0x0102004a"
- platform: ELKO_telnet
  switches:
    cabinet_switch_1_green_3:
      <<: *settings
      name: Cabinet Switch 1 Green 3
      device_id: "0x0102004c"
- platform: ELKO_telnet
  switches:
    cabinet_switch_1_red_1:
      <<: *settings
      name: Cabinet Switch 1 Red 1
      device_id: "0x01020049"
- platform: ELKO_telnet
  switches:
    cabinet_switch_1_red_2:
      <<: *settings
      name: Cabinet Switch 1 Red 2
      device_id: "0x0102004b"
- platform: ELKO_telnet
  switches:
    cabinet_switch_1_up_1:
      <<: *settings
      name: Cabinet Switch 1 Up 1
      device_id: "0x01010039"
- platform: ELKO_telnet
  switches:
    cabinet_switch_1_up_2:
      <<: *settings
      name: Cabinet Switch 1 Up 2
      device_id: "0x0101003b"
- platform: ELKO_telnet
  switches:
    cabinet_switch_1_up_3:
      <<: *settings
      name: Cabinet Switch 1 Up 3
      device_id: "0x0101003d"
- platform: ELKO_telnet
  switches:
    cabinet_switch_1_down_1:
      <<: *settings
      name: Cabinet Switch 1 Down 1
      device_id: "0x0101003a"
- platform: ELKO_telnet
  switches:
    cabinet_switch_1_down_2:
      <<: *settings
      name: Cabinet Switch 1 Down 2
      device_id: "0x0101003c"
- platform: ELKO_telnet
  switches:
    cabinet_switch_1_down_3:
      <<: *settings
      name: Cabinet Switch 1 Down 3
      device_id: "0x0101003e"
- platform: ELKO_telnet
  switches:
    cabinet_switch_1_red_3:
      <<: *settings
      name: Cabinet Switch 1 Red 3
      device_id: "0x0102004d"
- platform: ELKO_telnet
  switches:
    cabinet_light_wall:
      <<: *settings
      name: Cabinet Light Wall
      device_id: "0x01020011"
- platform: ELKO_telnet
  switches:
    cabinet_chandelier:
      <<: *settings
      name: Cabinet Chandelier
      device_id: "0x01020039"
- platform: ELKO_telnet
  switches:
    cabinet_camera:
      <<: *settings
      name: Cabinet Camera
      device_id: "0x01010004"
- platform: ELKO_telnet
  switches:
    cabinet_curtains_open:
      <<: *settings
      name: Cabinet Curtains Open
      device_id: "0x0102002f"
- platform: ELKO_telnet
  switches:
    cabinet_curtains_close:
      <<: *settings
      name: Cabinet Curtains Close
      device_id: "0x01020026"
- platform: ELKO_telnet
  switches:
    cabinet_rgb_red: &rgb
      name: Cabinet RGB Red
      resource: "192.168.88.246"
      device_id: "0x01040005"
      port: 1111
      command_on: "100"
      command_off: "0"
      value_template: >-
        {% if value > 0 %}
          True
        {% else %}
          False
        {% endif %}
      timeout: 0.1



- platform: template
  switches:
    cabinet_light_table_tmp:
      value_template: "{{ is_state('switch.cabinet_light_table', 'on') }}"
      turn_on:
        service: switch.turn_on
        target:
          entity_id: switch.cabinet_light_table
      turn_off:
        service: switch.turn_off
        target:
          entity_id: switch.cabinet_light_table
      icon_template: >-
        {% if is_state('switch.cabinet_light_table', 'on') %}
          mdi:desk-lamp-on
        {% else %}
          mdi:desk-lamp-off
        {% endif %}

- platform: template
  switches:
    cabinet_light_wall_tmp:
      value_template: "{{ is_state('switch.cabinet_light_wall', 'on') }}"
      turn_on:
        service: switch.turn_on
        target:
          entity_id: switch.cabinet_light_wall
      turn_off:
        service: switch.turn_off
        target:
          entity_id: switch.cabinet_light_wall
      icon_template: >-
        {% if is_state('switch.cabinet_light_wall', 'on') %}
          mdi:wall-sconce-flat
        {% else %}
          mdi:wall-sconce-flat-outline
        {% endif %}

- platform: template
  switches:
    cabinet_chandelier_tmp:
      value_template: "{{ is_state('switch.cabinet_chandelier', 'on') }}"
      turn_on:
        service: switch.turn_on
        target:
          entity_id: switch.cabinet_chandelier
      turn_off:
        service: switch.turn_off
        target:
          entity_id: switch.cabinet_chandelier
      icon_template: >-
        {% if is_state('switch.cabinet_chandelier', 'on') %}
          mdi:ceiling-light
        {% else %}
          mdi:ceiling-light-outline
        {% endif %}