# BigRoom Temperature
- platform: ELKO_telnet
  sensors:
    bigroom_temperature: &sensors
      friendly_name: "BigRoom Temperature"
      host: "192.168.88.246"
      device_id: "0x01050019"
      port: 1111
      device_class: 'temperature'
      unit_of_measurement: "°C"
- platform: ELKO_telnet
  sensors:
    bigroom_second_temperature:
      <<: *sensors
      friendly_name: "BigRoom Second Temperature"
      device_id: "0x01050014"
- platform: ELKO_telnet
  sensors:
    bigroom_humidity:
      <<: *sensors
      friendly_name: "BigRoom Humidity"
      device_id: "0x01050016"
      device_class: 'humidity'
      unit_of_measurement: "%"
- platform: ELKO_telnet
  sensors:
    bigroom_second_humidity:
      <<: *sensors
      friendly_name: "BigRoom Second Humidity"
      device_id: "0x0105001b"
      device_class: 'humidity'
      unit_of_measurement: "%"
- platform: ELKO_telnet
  sensors:
    bigroom_heater: &sensors2
      <<: *sensors
      friendly_name: "BigRoom Heater"
      device_id: "0x01020008"
      device_class: 'binary'
      unit_of_measurement: "on/off"
- platform: ELKO_telnet
  sensors:
    bigroom_curtains_open: &sensors3
      <<: *sensors
      friendly_name: "Bigroom Curtains Open"
      device_id: "0x01020073"
      device_class: 'binary'
      unit_of_measurement: "open/closed"
- platform: ELKO_telnet
  sensors:
    bigroom_curtains_close:
      <<: *sensors3
      friendly_name: "Bigroom Curtains Close"
      device_id: "0x01020072"
      unit_of_measurement: "closed/open"
- platform: ELKO_telnet
  sensors:
    bigroom_tule_open:
      <<: *sensors3
      friendly_name: "Bigroom Tule Open"
      device_id: "0x01020074"
- platform: ELKO_telnet
  sensors:
    bigroom_tule_close:
      <<: *sensors3
      friendly_name: "Bigroom Tule Close"
      device_id: "0x01020075"
      unit_of_measurement: "closed/open"
- platform: ELKO_telnet
  sensors:
    bigroom_chandelier:
      <<: *sensors2
      friendly_name: "Bigroom Chandelier"
      device_id: "0x01020005"
- platform: ELKO_telnet
  sensors:
    bigroom_backlight_window:
      <<: *sensors2
      friendly_name: "Bigroom Backlight Window"
      device_id: "0x01020009"
- platform: ELKO_telnet
  sensors:
    bigroom_backlight_door:
      <<: *sensors2
      friendly_name: "Bigroom Backlight Door"
      device_id: "0x0102002a"
- platform: ELKO_telnet
  sensors:
    bigroom_mirror:
      <<: *sensors2
      friendly_name: "Bigroom Mirror"
      device_id: "0x0102000a"
- platform: ELKO_telnet
  sensors:
    bigroom_point_light:
      <<: *sensors2
      friendly_name: "Bigroom Point Light"
      device_id: "0x0102002b"
