# Kitchen Floor Heater
- platform: ELKO_telnet
  switches:
    kitchen_floor_heater: &settings
      resource: "192.168.88.246"
      port: 1111
      command_on: "1"
      command_off: "0"
      value_template: >-
        {% if value == '1' %}
          True
        {% else %}
          False
        {% endif %}
      timeout: 0.1
      name: Kitchen Floor Heater
      device_id: "0x0102001a"
- platform: ELKO_telnet
  switches:
    kitchen_heater:
      <<: *settings
      name: Kitchen Heater
      device_id: "0x01020013"
- platform: ELKO_telnet
  switches:
    kitchen_curtains_open:
      <<: *settings
      name: Kitchen Curtains Open
      device_id: "0x01020076"
- platform: ELKO_telnet
  switches:
    kitchen_curtains_close:
      <<: *settings
      name: Kitchen Curtains Close
      device_id: "0x01020077"
- platform: ELKO_telnet
  switches:
    kitchen_tule_open:
      <<: *settings
      name: Kitchen Tule Open
      device_id: "0x01020079"
- platform: ELKO_telnet
  switches:
    kitchen_tule_close:
      <<: *settings
      name: Kitchen Tule Close
      device_id: "0x01020078"
- platform: ELKO_telnet
  switches:
    kitchen_chandelier:
      <<: *settings
      name: Kitchen Chandelier
      device_id: "0x01020006"
- platform: ELKO_telnet
  switches:
    kitchen_backlight_table:
      <<: *settings
      name: Kitchen Backlight Table
      device_id: "0x01020007"
- platform: ELKO_telnet
  switches:
    kitchen_backlight_wall:
      <<: *settings
      name: Kitchen Backlight Wall
      device_id: "0x0102000e"
- platform: ELKO_telnet
  switches:
    kitchen_point_lights_window:
      <<: *settings
      name: Kitchen Point Lights Window
      device_id: "0x01020037"
- platform: ELKO_telnet
  switches:
    kitchen_point_lights:
      <<: *settings
      name: Kitchen Point Lights
      device_id: "0x01020038"
- platform: ELKO_telnet
  switches:
    kitchen_switch_1_green_1:
      <<: *settings
      name: Kitchen Switch 1 Green 1
      device_id: "0x01020030"
- platform: ELKO_telnet
  switches:
    kitchen_switch_1_green_2:
      <<: *settings
      name: Kitchen Switch 1 Green 2
      device_id: "0x01020032"
- platform: ELKO_telnet
  switches:
    kitchen_switch_1_green_3:
      <<: *settings
      name: Kitchen Switch 1 Green 3
      device_id: "0x01020034"
- platform: ELKO_telnet
  switches:
    kitchen_switch_2_green_1:
      <<: *settings
      name: Kitchen Switch 2 Green 1
      device_id: "0x0102001f"
- platform: ELKO_telnet
  switches:
    kitchen_switch_2_green_2:
      <<: *settings
      name: Kitchen Switch 2 Green 2
      device_id: "0x01020021"
- platform: ELKO_telnet
  switches:
    kitchen_switch_1_red_1:
      <<: *settings
      name: Kitchen Switch 1 Red 1
      device_id: "0x01020031"
- platform: ELKO_telnet
  switches:
    kitchen_switch_1_red_2:
      <<: *settings
      name: Kitchen Switch 1 Red 2
      device_id: "0x01020033"
- platform: ELKO_telnet
  switches:
    kitchen_switch_1_red_3:
      <<: *settings
      name: Kitchen Switch 1 Red 3
      device_id: "0x01020035"
- platform: ELKO_telnet
  switches:
    kitchen_switch_2_red_1:
      <<: *settings
      name: Kitchen Switch 2 Red 1
      device_id: "0x01020020"
- platform: ELKO_telnet
  switches:
    kitchen_switch_2_red_2:
      <<: *settings
      name: Kitchen Switch 2 Red 2
      device_id: "0x01020022"
- platform: ELKO_telnet
  switches:
    kitchen_camera:
      <<: *settings
      name: Kitchen Camera
      device_id: "0x0101000e"



# Templates
# Kitchen Floor Heater Template
- platform: template
  switches:
    kitchen_floor_heater_tmp:
      value_template: "{{ is_state('switch.kitchen_floor_heater', 'on') }}"
      turn_on:
        service: switch.turn_on
        target:
          entity_id: switch.kitchen_floor_heater
      turn_off:
        service: switch.turn_off
        target:
          entity_id: switch.kitchen_floor_heater
      icon_template: >-
        {% if is_state('switch.kitchen_floor_heater', 'on') %}
          mdi:radiator
        {% else %}
          mdi:radiator-disabled
        {% endif %}
- platform: template
  switches:
    kitchen_heater_tmp:
      value_template: "{{ is_state('switch.kitchen_heater', 'on') }}"
      turn_on:
        service: switch.turn_on
        target:
          entity_id: switch.kitchen_heater
      turn_off:
        service: switch.turn_off
        target:
          entity_id: switch.kitchen_heater
      icon_template: >-
        {% if is_state('switch.kitchen_heater', 'on') %}
          mdi:radiator
        {% else %}
          mdi:radiator-disabled
        {% endif %}
- platform: template
  switches:
    kitchen_backlight_table_tmp:
      value_template: "{{ is_state('switch.kitchen_backlight_table', 'on') }}"
      turn_on:
        service: switch.turn_on
        target:
          entity_id: switch.kitchen_backlight_table
      turn_off:
        service: switch.turn_off
        target:
          entity_id: switch.kitchen_backlight_table
      icon_template: >-
        {% if is_state('switch.kitchen_backlight_table', 'on') %}
          mdi:globe-light
        {% else %}
          mdi:globe-light-outline
        {% endif %}
- platform: template
  switches:
    kitchen_chandelier_tmp:
      value_template: "{{ is_state('switch.kitchen_chandelier', 'on') }}"
      turn_on:
        service: switch.turn_on
        target:
          entity_id: switch.kitchen_chandelier
      turn_off:
        service: switch.turn_off
        target:
          entity_id: switch.kitchen_chandelier
      icon_template: >-
        {% if is_state('switch.kitchen_chandelier', 'on') %}
          mdi:ceiling-light
        {% else %}
          mdi:ceiling-light-outline
        {% endif %}
- platform: template
  switches:
    kitchen_backlight_wall_tmp:
      value_template: "{{ is_state('switch.kitchen_backlight_wall', 'on') }}"
      turn_on:
        service: switch.turn_on
        target:
          entity_id: switch.kitchen_backlight_wall
      turn_off:
        service: switch.turn_off
        target:
          entity_id: switch.kitchen_backlight_wall
      icon_template: >-
        {% if is_state('switch.kitchen_backlight_wall', 'on') %}
          mdi:wall-sconce-flat
        {% else %}
          mdi:wall-sconce-flat-outline
        {% endif %}
- platform: template
  switches:
    kitchen_point_lights_window_tmp:
      value_template: "{{ is_state('switch.kitchen_point_lights_window', 'on') }}"
      turn_on:
        service: switch.turn_on
        target:
          entity_id: switch.kitchen_point_lights_window
      turn_off:
        service: switch.turn_off
        target:
          entity_id: switch.kitchen_point_lights_window
      icon_template: >-
        {% if is_state('switch.kitchen_point_lights_window', 'on') %}
          mdi:lightbulb-group
        {% else %}
          mdi:lightbulb-group-off
        {% endif %}
- platform: template
  switches:
    kitchen_point_lights_tmp:
      value_template: "{{ is_state('switch.kitchen_point_lights', 'on') }}"
      turn_on:
        service: switch.turn_on
        target:
          entity_id: switch.kitchen_point_lights
      turn_off:
        service: switch.turn_off
        target:
          entity_id: switch.kitchen_point_lights
      icon_template: >-
        {% if is_state('switch.kitchen_point_lights', 'on') %}
          mdi:lightbulb-group
        {% else %}
          mdi:lightbulb-group-off
        {% endif %}