# SmallRoom Heater
- platform: ELKO_telnet
  switches:
    smallroom_chandelier: &settings
      resource: "192.168.88.246"
      port: 1111
      command_on: "1"
      command_off: "0"
      value_template: >-
        {% if value == '1' %}
          True
        {% else %}
          False
        {% endif %}
      timeout: 0.1
      name: Smallroom Chandelier
      device_id: "0x0102000d"
- platform: ELKO_telnet
  switches:
    smallroom_curtains_open:
      <<: *settings
      name: Smallroom Curtains Open
      device_id: "0x0102006e"
- platform: ELKO_telnet
  switches:
    smallroom_curtains_close:
      <<: *settings
      name: Smallroom Curtains Close
      device_id: "0x0102006f"
- platform: ELKO_telnet
  switches:
    smallroom_tule_open:
      <<: *settings
      name: Smallroom Tule Open
      device_id: "0x01020071"
- platform: ELKO_telnet
  switches:
    smallroom_tule_close:
      <<: *settings
      name: Smallroom Tule Close
      device_id: "0x01020070"
- platform: ELKO_telnet
  switches:
    smallroom_heater:
      <<: *settings
      name: SmallRoom Heater
      device_id: "0x01020004"
- platform: ELKO_telnet
  switches:
    smallroom_points_lights:
      <<: *settings
      name: Smallroom Points Lights
      device_id: "0x01020028"
- platform: ELKO_telnet
  switches:
    smallroom_backlight_wall:
      <<: *settings
      name: Smallroom Backlight Wall
      device_id: "0x0102003a"
- platform: ELKO_telnet
  switches:
    smallroom_switch_1_green_1:
      <<: *settings
      name: Smallroom Switch 1 Green 1
      device_id: "0x0102003c"
- platform: ELKO_telnet
  switches:
    smallroom_switch_1_green_2:
      <<: *settings
      name: Smallroom Switch 1 Green 2
      device_id: "0x0102003e"
- platform: ELKO_telnet
  switches:
    smallroom_switch_1_green_3:
      <<: *settings
      name: Smallroom Switch 1 Green 3
      device_id: "0x01020040"
- platform: ELKO_telnet
  switches:
    smallroom_switch_1_red_1:
      <<: *settings
      name: smallroom Switch 1 Red 1
      device_id: "0x0102003d"
- platform: ELKO_telnet
  switches:
    smallroom_switch_1_red_2:
      <<: *settings
      name: smallroom Switch 1 Red 2
      device_id: "0x0102003f"
- platform: ELKO_telnet
  switches:
    smallroom_switch_1_red_3:
      <<: *settings
      name: smallroom Switch 1 Red 3
      device_id: "0x01020041"
- platform: ELKO_telnet
  switches:
    smallroom_switch_1_light:
      <<: *settings
      name: smallroom Switch 1 Light
      device_id: "0x01020042"
- platform: ELKO_telnet
  switches:
    smallroom_camera:
      <<: *settings
      name: smallroom Camera
      device_id: "0x0101000e"

# Templates
# SmallRoom Heater Template
- platform: template
  switches:
    smallroom_heater_tmp:
      value_template: "{{ is_state('switch.smallroom_heater', 'on') }}"
      turn_on:
        service: switch.turn_on
        target:
          entity_id: switch.smallroom_heater
      turn_off:
        service: switch.turn_off
        target:
          entity_id: switch.smallroom_heater
      icon_template: >-
        {% if is_state('switch.smallroom_heater', 'on') %}
          mdi:radiator
        {% else %}
          mdi:radiator-disabled
        {% endif %}
- platform: template
  switches:
    smallroom_backlight_wall_tmp:
      value_template: "{{ is_state('switch.smallroom_backlight_wall', 'on') }}"
      turn_on:
        service: switch.turn_on
        target:
          entity_id:
            - switch.smallroom_backlight_wall
            - switch.smallroom_switch_1_green_1
      turn_off:
        service: switch.turn_off
        target:
          entity_id:
            - switch.smallroom_backlight_wall
            - switch.smallroom_switch_1_green_1
      icon_template: >-
        {% if is_state('switch.smallroom_backlight_wall', 'on') %}
          mdi:wall-sconce-flat
        {% else %}
          mdi:wall-sconce-flat-outline
        {% endif %}

- platform: template
  switches:
    smallroom_chandelier_tmp:
      value_template: "{{ is_state('switch.smallroom_chandelier', 'on') }}"
      turn_on:
        service: switch.turn_on
        target:
          entity_id:
            - switch.smallroom_chandelier
            - switch.smallroom_switch_1_green_3
      turn_off:
        service: switch.turn_off
        target:
          entity_id:
            - switch.smallroom_chandelier
            - switch.smallroom_switch_1_green_3
      icon_template: >-
        {% if is_state('switch.smallroom_chandelier', 'on') %}
          mdi:ceiling-light
        {% else %}
          mdi:ceiling-light-outline
        {% endif %}
- platform: template
  switches:
    smallroom_points_lights_tmp:
      value_template: "{{ is_state('switch.smallroom_points_lights', 'on') }}"
      turn_on:
        service: switch.turn_on
        target:
          entity_id:
            - switch.smallroom_points_lights
            - switch.smallroom_switch_1_green_2
      turn_off:
        service: switch.turn_off
        target:
          entity_id:
            - switch.smallroom_points_lights
            - switch.smallroom_switch_1_green_2
      icon_template: >-
        {% if is_state('switch.smallroom_points_lights', 'on') %}
          mdi:lightbulb-group
        {% else %}
          mdi:lightbulb-group-off
        {% endif %}