# BigRoom Temperature
- platform: command_line
  unique_id: bigroom_temperature
  name: BigRoom Temperature
  command: "python3 custom_components/ELKO_telnet/get_data.py -h 192.168.88.246 -p 1111 -i 0x01050019"
  unit_of_measurement: "째C"
  value_template: "{{ value | multiply(0.01) | round(1) }}"
- platform: command_line
  unique_id: bigroom_second_temperature
  name: BigRoom Second Temperature
  command: "python3 custom_components/ELKO_telnet/get_data.py -h 192.168.88.246 -p 1111 -i 0x01050014"
  unit_of_measurement: "째C"
  value_template: "{{ value | multiply(0.01) | round(1) }}"
- platform: command_line
  unique_id: bigroom_humidity
  name: BigRoom Humidity
  command: "python3 custom_components/ELKO_telnet/get_data.py -h 192.168.88.246 -p 1111 -i 0x01050016"
  unit_of_measurement: "째C"
  value_template: "{{ value | multiply(0.01) | round(1) }}"
- platform: command_line
  unique_id: bigroom_second_humidity
  name: BigRoom Second Humidity
  command: "python3 custom_components/ELKO_telnet/get_data.py -h 192.168.88.246 -p 1111 -i 0x0105001b"
  unit_of_measurement: "째C"
  value_template: "{{ value | multiply(0.01) | round(1) }}"
- platform: command_line
  unique_id: bigroom_heater
  name: BigRoom Heater
  command: "python3 custom_components/ELKO_telnet/get_data.py -h 192.168.88.246 -p 1111 -i 0x01020008"
  value_template: >-
    {% if value == '1' %}
      on
    {% else %}
      off
    {% endif %}
- platform: command_line
  unique_id: bigroom_curtains_open
  name: Bigroom Curtains Open
  command: "python3 custom_components/ELKO_telnet/get_data.py -h 192.168.88.246 -p 1111 -i 0x01020073"
  value_template: >-
    {% if value == '1' %}
      open
    {% else %}
      closed
    {% endif %}
- platform: command_line
  unique_id: bigroom_curtains_close
  name: Bigroom Curtains Close
  command: "python3 custom_components/ELKO_telnet/get_data.py -h 192.168.88.246 -p 1111 -i 0x01020072"
  value_template: >-
    {% if value == '1' %}
      closed
    {% else %}
      open
    {% endif %}
- platform: command_line
  unique_id: bigroom_tule_open
  name: Bigroom Tule Open
  command: "python3 custom_components/ELKO_telnet/get_data.py -h 192.168.88.246 -p 1111 -i 0x01020074"
  value_template: >-
    {% if value == '1' %}
      open
    {% else %}
      closed
    {% endif %}
- platform: command_line
  unique_id: bigroom_tule_close
  name: Bigroom Tule Close
  command: "python3 custom_components/ELKO_telnet/get_data.py -h 192.168.88.246 -p 1111 -i 0x01020075"
  value_template: >-
    {% if value == '1' %}
      closed
    {% else %}
      open
    {% endif %}
- platform: command_line
  unique_id: bigroom_chandelier
  name: Bigroom Chandelier
  command: "python3 custom_components/ELKO_telnet/get_data.py -h 192.168.88.246 -p 1111 -i 0x01020005"
  value_template: >-
    {% if value == '1' %}
      on
    {% else %}
      off
    {% endif %}
- platform: command_line
  unique_id: bigroom_backlight_window
  name: Bigroom Backlight Window
  command: "python3 custom_components/ELKO_telnet/get_data.py -h 192.168.88.246 -p 1111 -i 0x01020009"
  value_template: >-
    {% if value == '1' %}
      on
    {% else %}
      off
    {% endif %}
- platform: command_line
  unique_id: bigroom_backlight_door
  name: Bigroom Backlight Door
  command: "python3 custom_components/ELKO_telnet/get_data.py -h 192.168.88.246 -p 1111 -i 0x0102002a"
  value_template: >-
    {% if value == '1' %}
      on
    {% else %}
      off
    {% endif %}
- platform: command_line
  unique_id: bigroom_mirror
  name: Bigroom Mirror
  command: "python3 custom_components/ELKO_telnet/get_data.py -h 192.168.88.246 -p 1111 -i 0x0102000a"
  value_template: >-
    {% if value == '1' %}
      on
    {% else %}
      off
    {% endif %}
- platform: command_line
  unique_id: bigroom_point_light
  name: Bigroom Point Light
  command: "python3 custom_components/ELKO_telnet/get_data.py -h 192.168.88.246 -p 1111 -i 0x0102002b"
  value_template: >-
    {% if value == '1' %}
      on
    {% else %}
      off
    {% endif %}
