# BigRoom Heater
- platform: ELKO_telnet
  switches:
    bigroom_heater: &settings
      resource: "192.168.88.246"
      port: 1111
      command_on: "0"
      command_off: "1"
      value_template: >-
        {% if value == '1' %}
          True
        {% else %}
          False
        {% endif %}
      timeout: 0.1
      name: BigRoom Heater
      device_id: "0x01020008"
- platform: ELKO_telnet
  switches:
    bigroom_curtains_open:
      <<: *settings
      name: Bigroom Curtains Open
      device_id: "0x01020072"
- platform: ELKO_telnet
  switches:
    bigroom_curtains_close:
      <<: *settings
      name: Bigroom Curtains Close
      device_id: "0x01020073"
- platform: ELKO_telnet
  switches:
    bigroom_tule_open:
      <<: *settings
      name: Bigroom Tule Open
      device_id: "0x01020075"
- platform: ELKO_telnet
  switches:
    bigroom_tule_close:
      <<: *settings
      name: Bigroom Tule Close
      device_id: "0x01020074"
- platform: ELKO_telnet
  switches:
    bigroom_chandelier:
      <<: *settings
      name: Bigroom Chandelier
      device_id: "0x01020005"
- platform: ELKO_telnet
  switches:
    bigroom_backlight_window:
      <<: *settings
      name: Bigroom Backlight Window
      device_id: "0x01020009"
- platform: ELKO_telnet
  switches:
    bigroom_backlight_door:
      <<: *settings
      name: Bigroom Backlight Door
      device_id: "0x0102002a"
- platform: ELKO_telnet
  switches:
    bigroom_mirror:
      <<: *settings
      name: Bigroom Mirror
      device_id: "0x0102000a"
- platform: ELKO_telnet
  switches:
    bigroom_point_light:
      <<: *settings
      name: Bigroom Point Light
      device_id: "0x0102002b"

# Templates
# BigRoom Heater Template
- platform: template
  switches:
    bigroom_heater_tmp:
      value_template: "{{ is_state('switch.bigroom_heater', 'on') }}"
      turn_on:
        service: switch.turn_on
        target:
          entity_id: switch.bigroom_heater
      turn_off:
        service: switch.turn_off
        target:
          entity_id: switch.bigroom_heater
      icon_template: >-
        {% if is_state('switch.bigroom_heater', 'on') %}
          mdi:radiator
        {% else %}
          mdi:radiator-disabled
        {% endif %}
- platform: template
  switches:
    bigroom_mirror_tmp:
      value_template: "{{ is_state('switch.bigroom_mirror', 'off') }}"
      turn_on:
        service: switch.turn_on
        target:
          entity_id: switch.bigroom_mirror
      turn_off:
        service: switch.turn_off
        target:
          entity_id: switch.bigroom_mirror
      icon_template: >-
        {% if is_state('switch.bigroom_mirror', 'off') %}
          mdi:wall-sconce-flat
        {% else %}
          mdi:wall-sconce-flat-outline
        {% endif %}

- platform: template
  switches:
    bigroom_point_light_tmp:
      value_template: "{{ is_state('switch.bigroom_point_light', 'off') }}"
      turn_on:
        service: switch.turn_on
        target:
          entity_id: switch.bigroom_point_light
      turn_off:
        service: switch.turn_off
        target:
          entity_id: switch.bigroom_point_light
      icon_template: >-
        {% if is_state('switch.bigroom_point_light', 'off') %}
          mdi:lightbulb-group
        {% else %}
          mdi:lightbulb-group-off
        {% endif %}
- platform: template
  switches:
    bigroom_chandelier_tmp:
      value_template: "{{ is_state('switch.bigroom_chandelier', 'off') }}"
      turn_on:
        service: switch.turn_on
        target:
          entity_id: switch.bigroom_chandelier
      turn_off:
        service: switch.turn_off
        target:
          entity_id: switch.bigroom_chandelier
      icon_template: >-
        {% if is_state('switch.bigroom_chandelier', 'off') %}
          mdi:ceiling-light
        {% else %}
          mdi:ceiling-light-outline
        {% endif %}
- platform: template
  switches:
    bigroom_backlight_window_tmp:
      value_template: "{{ is_state('switch.bigroom_backlight_window', 'off') }}"
      turn_on:
        service: switch.turn_on
        target:
          entity_id: switch.bigroom_backlight_window
      turn_off:
        service: switch.turn_off
        target:
          entity_id: switch.bigroom_backlight_window
      icon_template: >-
        {% if is_state('switch.bigroom_backlight_window', 'off') %}
          mdi:lamps
        {% else %}
          mdi:lamps-outline
        {% endif %}
- platform: template
  switches:
    bigroom_backlight_door_tmp:
      value_template: "{{ is_state('switch.bigroom_backlight_door', 'off') }}"
      turn_on:
        service: switch.turn_on
        target:
          entity_id: switch.bigroom_backlight_door
      turn_off:
        service: switch.turn_off
        target:
          entity_id: switch.bigroom_backlight_door
      icon_template: >-
        {% if is_state('switch.bigroom_backlight_door', 'off') %}
          mdi:lamps
        {% else %}
          mdi:lamps-outline
        {% endif %}