- id: kitchen_point_lights
  alias: kitchen Points Light
  description: ''
  trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id:
    - sensor.kitchen_point_lights
  condition: []
  action:
  - condition: template
    value_template: "{{ states('switch.kitchen_point_lights_tmp') != states('sensor.kitchen_point_lights') }}"
  - service: switch.turn_{{states('sensor.kitchen_point_lights')}}
    data: {}
    target:
      entity_id: switch.kitchen_point_lights_tmp
  mode: single
- id: kitchen_point_lights_window
  alias: Kitchen Point Lights Window
  description: ''
  trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id:
    - sensor.kitchen_point_lights_window
  condition: []
  action:
  - condition: template
    value_template: "{{ states('switch.kitchen_point_lights_window_tmp') != states('sensor.kitchen_point_lights_window') }}"
  - service: switch.turn_{{states('sensor.kitchen_point_lights_window')}}
    data: {}
    target:
      entity_id: switch.kitchen_point_lights_window_tmp
  mode: single
- id: kitchen_backlight_wall
  alias: Kitchen Backlight Wall
  description: ''
  trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id:
    - sensor.kitchen_backlight_wall
  condition: []
  action:
  - condition: template
    value_template: "{{ states('switch.kitchen_backlight_wall_tmp') != states('sensor.kitchen_backlight_wall') }}"
  - service: switch.turn_{{states('sensor.kitchen_backlight_wall')}}
    data: {}
    target:
      entity_id: switch.kitchen_backlight_wall_tmp
  mode: single
- id: kitchen_backlight_table
  alias: Kitchen Backlight Table
  description: ''
  trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id:
    - sensor.kitchen_backlight_table
  condition: []
  action:
  - condition: template
    value_template: "{{ states('switch.kitchen_backlight_table_tmp') != states('sensor.kitchen_backlight_table') }}"
  - service: switch.turn_{{states('sensor.kitchen_backlight_table')}}
    data: {}
    target:
      entity_id: switch.kitchen_backlight_table_tmp
  mode: single
- id: kitchen_chandelier
  alias: Kitchen Chandelier
  description: ''
  trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id:
    - sensor.kitchen_chandelier
  condition: []
  action:
  - condition: template
    value_template: "{{ states('switch.kitchen_chandelier_tmp') != states('sensor.kitchen_chandelier') }}"
  - service: switch.turn_{{states('sensor.kitchen_chandelier')}}
    data: {}
    target:
      entity_id: switch.kitchen_chandelier_tmp
  mode: single
- id: kitchen_curtain
  alias: Kitchen Curtains
  description: ''
  trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id:
    - sensor.kitchen_curtains_open
  condition: []
  action:
  - condition: template
    value_template: "{{ states('cover.kitchen_curtain') != states('sensor.kitchen_curtains_open') }}"
  - service: cover.{{ states('sensor.kitchen_curtains_open') | replace("closed", "close") }}_cover
    data: {}
    target:
      entity_id: cover.kitchen_curtain
  mode: single
- id: kitchen_tule
  alias: Kitchen Tule
  description: ''
  trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id:
    - sensor.kitchen_tule_open
  condition: []
  action:
  - condition: template
    value_template: "{{ states('cover.kitchen_tule') != states('sensor.kitchen_tule_open') }}"
  - service: cover.{{ states('sensor.kitchen_tule_open') | replace("closed", "close") }}_cover
    data: {}
    target:
      entity_id: cover.kitchen_tule
  mode: single
- id: 'kitchen_switch_1_up_1'
  alias: Kitchen Switch 1 Up 1
  description: 'Kitchen Switch 1 Up 1'
  trigger:
  - platform: webhook
    webhook_id: '0x01010023'
  - platform: webhook
    webhook_id: '0x01010020'
  condition:
  - condition: template
    value_template: "{{ trigger.json.event_id == '29' and trigger.json.device_state == '1' }}"
  action:
  - choose:
    - conditions:
      - condition: template
        value_template: "{{ is_state('switch.kitchen_point_lights_window', 'off') }}"
      sequence:
      - service: switch.turn_on
        data: {}
        target:
          entity_id: switch.kitchen_point_lights_window
      - service: switch.turn_on
        data: {}
        target:
          entity_id: switch.kitchen_switch_1_green_1
      - service: switch.turn_on
        data: {}
        target:
          entity_id: switch.kitchen_switch_2_red_2
    - conditions:
      - condition: template
        value_template: "{{ is_state('switch.kitchen_point_lights_window', 'on') }}"
      sequence:
      - service: switch.turn_off
        data: {}
        target:
          entity_id: switch.kitchen_point_lights_window
      - service: switch.turn_off
        data: {}
        target:
          entity_id: switch.kitchen_switch_1_green_1
      - service: switch.turn_off
        data: {}
        target:
          entity_id: switch.kitchen_switch_2_red_2
  mode: single
- id: 'kitchen_switch_1_up_2'
  alias: Kitchen Switch 1 Up 2
  description: 'Kitchen Switch 1 Up 2'
  trigger:
  - platform: webhook
    webhook_id: '0x01010025'
  condition:
  - condition: template
    value_template: "{{ trigger.json.event_id == '29' and trigger.json.device_state == '1' }}"
  action:
  - choose:
    - conditions:
      - condition: template
        value_template: "{{ is_state('switch.kitchen_point_lights', 'off') }}"
      sequence:
      - service: switch.turn_on
        data: {}
        target:
          entity_id: switch.kitchen_point_lights
      - service: switch.turn_on
        data: {}
        target:
          entity_id: switch.kitchen_switch_1_green_2
    - conditions:
      - condition: template
        value_template: "{{ is_state('switch.kitchen_point_lights', 'on') }}"
      sequence:
      - service: switch.turn_off
        data: {}
        target:
          entity_id: switch.kitchen_point_lights
      - service: switch.turn_off
        data: {}
        target:
          entity_id: switch.kitchen_switch_1_green_2
  mode: single
- id: 'kitchen_switch_1_up_3'
  alias: Kitchen Switch 1 Up 3
  description: 'Kitchen Switch 1 Up 3'
  trigger:
  - platform: webhook
    webhook_id: '0x01010027'
  - platform: webhook
    webhook_id: '0x0101001f'
  condition:
  - condition: template
    value_template: "{{ trigger.json.event_id == '29' and trigger.json.device_state == '1' }}"
  action:
  - choose:
    - conditions:
      - condition: template
        value_template: "{{ is_state('switch.kitchen_chandelier', 'off') }}"
      sequence:
      - service: switch.turn_on
        data: {}
        target:
          entity_id: switch.kitchen_chandelier
      - service: switch.turn_on
        data: {}
        target:
          entity_id: switch.kitchen_switch_1_green_3
      - service: switch.turn_on
        data: {}
        target:
          entity_id: switch.kitchen_switch_2_green_2
    - conditions:
      - condition: template
        value_template: "{{ is_state('switch.kitchen_chandelier', 'on') }}"
      sequence:
      - service: switch.turn_off
        data: {}
        target:
          entity_id: switch.kitchen_chandelier
      - service: switch.turn_off
        data: {}
        target:
          entity_id: switch.kitchen_switch_1_green_3
      - service: switch.turn_off
        data: {}
        target:
          entity_id: switch.kitchen_switch_2_green_2
  mode: single
- id: 'kitchen_switch_1_down_1'
  alias: Kitchen Switch 1 Down 1
  description: 'Kitchen Switch 1 Down 1'
  trigger:
  - platform: webhook
    webhook_id: '0x01010024'
  condition:
  - condition: template
    value_template: "{{ trigger.json.event_id == '29' and trigger.json.device_state == '1' }}"
  action:
  - choose:
    - conditions:
      - condition: template
        value_template: "{{ is_state('switch.kitchen_backlight_table', 'off') }}"
      sequence:
      - service: switch.turn_on
        data: {}
        target:
          entity_id: switch.kitchen_backlight_table
      - service: switch.turn_on
        data: {}
        target:
          entity_id: switch.kitchen_switch_1_red_1
    - conditions:
      - condition: template
        value_template: "{{ is_state('switch.kitchen_backlight_table', 'on') }}"
      sequence:
      - service: switch.turn_off
        data: {}
        target:
          entity_id: switch.kitchen_backlight_table
      - service: switch.turn_off
        data: {}
        target:
          entity_id: switch.kitchen_switch_1_red_1
  mode: single
- id: 'kitchen_switch_1_down_2'
  alias: Kitchen Switch 1 Down 2
  description: 'Kitchen Switch 1 Down 2'
  trigger:
  - platform: webhook
    webhook_id: '0x01010026'
  condition:
  - condition: template
    value_template: "{{ trigger.json.event_id == '29' and trigger.json.device_state == '1' }}"
  action:
  - choose:
    - conditions:
      - condition: template
        value_template: "{{ is_state('switch.kitchen_backlight_wall', 'off') }}"
      sequence:
      - service: switch.turn_on
        data: {}
        target:
          entity_id: switch.kitchen_backlight_wall
      - service: switch.turn_on
        data: {}
        target:
          entity_id: switch.kitchen_switch_1_red_2
    - conditions:
      - condition: template
        value_template: "{{ is_state('switch.kitchen_backlight_wall', 'on') }}"
      sequence:
      - service: switch.turn_off
        data: {}
        target:
          entity_id: switch.kitchen_backlight_wall
      - service: switch.turn_off
        data: {}
        target:
          entity_id: switch.kitchen_switch_1_red_2
  mode: single
- id: 'kitchen_switch_1_down_3'
  alias: Kitchen Switch 1 Down 3
  description: 'Kitchen Switch 1 Down 3'
  trigger:
  - platform: webhook
    webhook_id: '0x01010028'
  condition:
  - condition: template
    value_template: "{{ trigger.json.event_id == '29' and trigger.json.device_state == '1' }}"
  action:
  - choose:
    - conditions: []
      sequence:
      - service: switch.turn_off
        data: {}
        target:
          entity_id: switch.kitchen_backlight_wall
      - service: switch.turn_off
        data: {}
        target:
          entity_id: switch.kitchen_switch_1_red_2
      - service: switch.turn_off
        data: {}
        target:
          entity_id: switch.kitchen_backlight_table
      - service: switch.turn_off
        data: {}
        target:
          entity_id: switch.kitchen_switch_1_red_1
      - service: switch.turn_off
        data: {}
        target:
          entity_id: switch.kitchen_chandelier
      - service: switch.turn_off
        data: {}
        target:
          entity_id: switch.kitchen_switch_1_green_3
      - service: switch.turn_off
        data: {}
        target:
          entity_id: switch.kitchen_point_lights
      - service: switch.turn_off
        data: {}
        target:
          entity_id: switch.kitchen_switch_1_green_2
      - service: switch.turn_off
        data: {}
        target:
          entity_id: switch.kitchen_point_lights_window
      - service: switch.turn_off
        data: {}
        target:
          entity_id: switch.kitchen_switch_1_green_1
      - service: switch.turn_off
        data: {}
        target:
          entity_id: switch.kitchen_switch_1_red_3
      - service: switch.turn_off
        data: {}
        target:
          entity_id: switch.kitchen_switch_2_red_2
  mode: single
- id: 'kitchen_switch_2_up_1'
  alias: Kitchen Switch 2 Up 1
  description: 'Kitchen Switch 2 Up 1'
  trigger:
  - platform: webhook
    webhook_id: '0x0101001d'
  condition:
  - condition: template
    value_template: "{{ trigger.json.event_id == '29' and trigger.json.device_state == '1' }}"
  action:
  - choose:
    - conditions:
      - condition: template
        value_template: "{{ is_state('switch.kitchen_curtains_open', 'off') }}"
      sequence:
      - service: switch.turn_off
        data: {}
        target:
          entity_id: switch.kitchen_curtains_close
      - service: switch.turn_on
        data: {}
        target:
          entity_id: switch.kitchen_curtains_open
      - service: switch.turn_on
        data: {}
        target:
          entity_id: switch.kitchen_switch_2_green_1
    - conditions:
      - condition: template
        value_template: "{{ is_state('switch.kitchen_curtains_open', 'on') }}"
      sequence:
      - service: switch.turn_off
        data: {}
        target:
          entity_id: switch.kitchen_curtains_open
      - service: switch.turn_off
        data: {}
        target:
          entity_id: switch.kitchen_switch_2_green_1
      - service: switch.turn_on
        data: {}
        target:
          entity_id: switch.kitchen_curtains_close
  mode: single
- id: 'kitchen_switch_2_down_1'
  alias: Kitchen Switch 2 Down 1
  description: 'Kitchen Switch 2 Down 1'
  trigger:
  - platform: webhook
    webhook_id: '0x0101001e'
  condition:
  - condition: template
    value_template: "{{ trigger.json.event_id == '29' and trigger.json.device_state == '1' }}"
  action:
  - choose:
    - conditions:
      - condition: template
        value_template: "{{ is_state('switch.kitchen_tule_open', 'off') }}"
      sequence:
      - service: switch.turn_off
        data: {}
        target:
          entity_id: switch.kitchen_tule_close
      - service: switch.turn_on
        data: {}
        target:
          entity_id: switch.kitchen_tule_open
      - service: switch.turn_on
        data: {}
        target:
          entity_id: switch.kitchen_switch_2_red_1
    - conditions:
      - condition: template
        value_template: "{{ is_state('switch.kitchen_tule_open', 'on') }}"
      sequence:
      - service: switch.turn_off
        data: {}
        target:
          entity_id: switch.kitchen_tule_open
      - service: switch.turn_off
        data: {}
        target:
          entity_id: switch.kitchen_switch_2_red_1
      - service: switch.turn_on
        data: {}
        target:
          entity_id: switch.kitchen_tule_close
  mode: single
- id: 'kitchen_motion'
  alias: Kitchen Motion
  description: 'Kitchen Motion'
  trigger:
  - platform: webhook
    webhook_id: '0x01010007'
  condition:
  - condition: time
    after: "20:00:00"
    before: "08:00:00"
  action:
  - choose:
    - conditions: []
      sequence:
      - service: switch.turn_on
        data: {}
        target:
          entity_id: switch.kitchen_backlight_wall
      - service: switch.turn_on
        data: {}
        target:
          entity_id: switch.kitchen_switch_1_red_2
      - delay:
          hours: 0
          minutes: 3
          seconds: 0
          milliseconds: 0
      - service: switch.turn_off
        data: {}
        target:
          entity_id: switch.kitchen_backlight_wall
      - service: switch.turn_off
        data: {}
        target:
          entity_id: switch.kitchen_switch_1_red_2
  mode: single
- id: 'kitchen_camera'
  alias: Kitchen Camera
  description: 'Kitchen Camera'
  trigger:
  - platform: webhook
    webhook_id: '0x0101000e'
  condition:
  - condition: template
    value_template: "{{ trigger.json.event_id == '29' and trigger.json.device_state == '1' }}"
  action:
  - choose:
    - sequence:
      - service: light.turn_on
        data:
          rgb_color:
            - 255
            - 128
            - 128
        target:
          entity_id: light.kitchen_rgb
      - delay:
          hours: 0
          minutes: 0
          seconds: 30
          milliseconds: 0
      - service: light.turn_off
        data: {}
        target:
          entity_id: lights.kitchen_rgb
  mode: single
