# Kitchen Temperature
- platform: command_line
  unique_id: kitchen_temperature
  name: Kitchen Temperature
  command: "python3 custom_components/ELKO_telnet/get_data.py -h 192.168.88.246 -p 1111 -i 0x01050003"
  unit_of_measurement: "°C"
  value_template: "{{ value | multiply(0.01) | round(1) }}"
- platform: command_line
  unique_id: kitchen_window_temperature
  name: Kitchen Window Temperature
  command: "python3 custom_components/ELKO_telnet/get_data.py -h 192.168.88.246 -p 1111 -i 0x0105000a"
  unit_of_measurement: "°C"
  value_template: "{{ value | multiply(0.01) | round(1) }}"
- platform: command_line
  unique_id: kitchen_door_temperature
  name: Kitchen Door Temperature
  command: "python3 custom_components/ELKO_telnet/get_data.py -h 192.168.88.246 -p 1111 -i 0x0105000e"
  unit_of_measurement: "°C"
  value_template: "{{ value | multiply(0.01) | round(1) }}"
- platform: command_line
  unique_id: kitchen_humidity
  name: Kitchen Humidity
  command: "python3 custom_components/ELKO_telnet/get_data.py -h 192.168.88.246 -p 1111 -i 0x0105000c"
  unit_of_measurement: "%"
  value_template: "{{ value | multiply(0.01) | round(1) }}"
