# Kitchen Temperature
- platform: ELKO_telnet
  sensors:
    kitchen_temperature: &sensors
      friendly_name: "Kitchen Temperature"
      host: "192.168.88.246"
      device_id: "0x01050003"
      port: 1111
      device_class: 'temperature'
      unit_of_measurement: "°C"
- platform: ELKO_telnet
  sensors:
    kitchen_window_temperature:
      <<: *sensors
      friendly_name: "Kitchen Window Temperature"
      device_id: "0x0105000a"
- platform: ELKO_telnet
  sensors:
    kitchen_door_temperature:
      <<: *sensors
      friendly_name: "Kitchen Door Temperature"
      device_id: "0x0105000e"
- platform: ELKO_telnet
  sensors:
    kitchen_humidity:
      <<: *sensors
      friendly_name: "Kitchen Humidity"
      device_id: "0x0105000c"
      device_class: 'humidity'
      unit_of_measurement: "%"
- platform: ELKO_telnet
  sensors:
    kitchen_floor_heater: &sensors2
      <<: *sensors
      friendly_name: "Kitchen Floor Heater"
      device_id: "0x0102001a"
      device_class: 'binary'
      unit_of_measurement: "on/off"
- platform: ELKO_telnet
  sensors:
    kitchen_heater:
      <<: *sensors2
      friendly_name: "Kitchen Heater"
      device_id: "0x01020013"
- platform: ELKO_telnet
  sensors:
    kitchen_move_detector:
      <<: *sensors2
      friendly_name: "Kitchen Move Detector"
      device_id: "0x01010007"
- platform: ELKO_telnet
  sensors:
    kitchen_chandelier:
      <<: *sensors2
      friendly_name: "Kitchen Chandelier"
      device_id: "0x01020006"
- platform: ELKO_telnet
  sensors:
    kitchen_backlight_table:
      <<: *sensors2
      friendly_name: "Kitchen Backlight Table"
      device_id: "0x01020007"
- platform: ELKO_telnet
  sensors:
    kitchen_backlight_wall:
      <<: *sensors2
      friendly_name: "Kitchen Backlight Wall"
      device_id: "0x0102000e"
- platform: ELKO_telnet
  sensors:
    kitchen_point_lights_window:
      <<: *sensors2
      friendly_name: "Kitchen Point Lights Window"
      device_id: "0x01020037"
- platform: ELKO_telnet
  sensors:
    kitchen_point_lights:
      <<: *sensors2
      friendly_name: "Kitchen Point Lights"
      device_id: "0x01020038"
- platform: ELKO_telnet
  sensors:
    kitchen_curtains_open: &sensors3
      <<: *sensors
      friendly_name: "Kitchen Curtains Open"
      device_id: "0x01020076"
      device_class: 'binary'
      unit_of_measurement: "open/closed"
- platform: ELKO_telnet
  sensors:
    kitchen_curtains_close:
      <<: *sensors3
      friendly_name: "Kitchen Curtains Close"
      device_id: "0x01020077"
      unit_of_measurement: "closed/open"
- platform: ELKO_telnet
  sensors:
    kitchen_tule_open:
      <<: *sensors3
      friendly_name: "Kitchen Tule Open"
      device_id: "0x01020079"
- platform: ELKO_telnet
  sensors:
    kitchen_tule_close:
      <<: *sensors3
      friendly_name: "Kitchen Tule Close"
      device_id: "0x01020078"
      unit_of_measurement: "closed/open"
