# Kitchen Floor Heater
- platform: ELKO_telnet
  switches:
    kitchen_floor_heater: &settings
      resource: "192.168.88.246"
      port: 1111
      command_on: "1"
      command_off: "0"
      value_template: >-
        {% if value == '1' %}
          True
        {% else %}
          False
        {% endif %}
      timeout: 0.1
      name: Kitchen Floor Heater
      device_id: "0x0102001a"
- platform: ELKO_telnet
  switches:
    kitchen_heater:
      <<: *settings
      command_on: "0"
      command_off: "1"
      name: Kitchen Heater
      device_id: "0x01020013"
# Templates
# Kitchen Floor Heater Template
- platform: template
  switches:
    kitchen_floor_heater_tmp:
      value_template: "{{ is_state('switch.kitchen_floor_heater', 'on') }}"
      turn_on:
        service: switch.turn_on
        target:
          entity_id: switch.kitchen_floor_heater
      turn_off:
        service: switch.turn_off
        target:
          entity_id: switch.kitchen_floor_heater
      icon_template: >-
        {% if is_state('switch.kitchen_floor_heater', 'on') %}
          mdi:radiator
        {% else %}
          mdi:radiator-disabled
        {% endif %}
- platform: template
  switches:
    kitchen_heater_tmp:
      value_template: "{{ is_state('switch.kitchen_heater', 'on') }}"
      turn_on:
        service: switch.turn_on
        target:
          entity_id: switch.kitchen_heater
      turn_off:
        service: switch.turn_off
        target:
          entity_id: switch.kitchen_heater
      icon_template: >-
        {% if is_state('switch.kitchen_heater', 'on') %}
          mdi:radiator
        {% else %}
          mdi:radiator-disabled
        {% endif %}