- id: 'wc_switch_1_up_1'
  alias: WC Switch 1 Up 1
  description: 'WC Switch 1 Up 1'
  trigger:
  - platform: webhook
    webhook_id: '0x01010047'
  condition:
  - condition: template
    value_template: "{{ trigger.json.event_id == '29' and trigger.json.device_state == '1' }}"
  action:
  - choose:
    - conditions:
      - condition: template
        value_template: "{{ is_state('switch.wc_pointslights', 'off') }}"
      sequence:
      - service: switch.turn_on
        data: {}
        target:
          entity_id: switch.wc_pointslights
      - service: switch.turn_on
        data: {}
        target:
          entity_id: switch.wc_fan
      - service: switch.turn_on
        data: {}
        target:
          entity_id: switch.wc_switch_1_green_1
      - service: switch.turn_on
        data: {}
        target:
          entity_id: switch.wc_switch_1_red_1
    - conditions:
      - condition: template
        value_template: "{{ is_state('switch.wc_pointslights', 'on') }}"
      sequence:
      - service: switch.turn_off
        data: {}
        target:
          entity_id: switch.wc_pointslights
      - service: switch.turn_off
        data: {}
        target:
          entity_id: switch.wc_switch_1_green_1
      - delay: 15
      - choose:
        - conditions:
          - condition: template
            value_template: "{{ is_state('switch.wc_pointslights', 'off') }}"
          sequence:
          - service: switch.turn_off
            data: {}
            target:
              entity_id: switch.wc_fan
          - service: switch.turn_off
            data: {}
            target:
              entity_id: switch.wc_switch_1_red_1
  mode: single
- id: 'wc_switch_1_down_1'
  alias: WC Switch 1 Down 1
  description: 'WC Switch 1 Down 1'
  trigger:
  - platform: webhook
    webhook_id: '0x01010048'
  condition:
  - condition: template
    value_template: "{{ trigger.json.event_id == '29' and trigger.json.device_state == '1' }}"
  action:
  - choose:
    - conditions:
      - condition: template
        value_template: "{{ is_state('switch.wc_fan', 'off') }}"
      sequence:
      - service: switch.turn_on
        data: {}
        target:
          entity_id: switch.wc_fan
      - service: switch.turn_on
        data: {}
        target:
          entity_id: switch.wc_switch_1_red_1
    - conditions:
      - condition: template
        value_template: "{{ is_state('switch.wc_fan', 'on') }}"
      sequence:
      - service: switch.turn_off
        data: {}
        target:
          entity_id: switch.wc_fan
      - service: switch.turn_off
        data: {}
        target:
          entity_id: switch.wc_switch_1_red_1
  mode: single
- id: 'wc_switch_1_up_2'
  alias: WC Switch 1 Up 2
  description: 'WC Switch 1 Up 2'
  trigger:
  - platform: webhook
    webhook_id: '0x01010049'
  - platform: webhook
    webhook_id: '0x01010019'
  condition:
  - condition: template
    value_template: "{{ trigger.json.event_id == '29' and trigger.json.device_state == '1' }}"
  action:
  - choose:
    - conditions:
      - condition: template
        value_template: "{{ is_state('switch.wc_mirror', 'off') }}"
      sequence:
      - service: switch.turn_on
        data: {}
        target:
          entity_id: switch.wc_mirror
      - service: switch.turn_on
        data: {}
        target:
          entity_id: switch.wc_switch_1_green_2
      - service: switch.turn_on
        data: {}
        target:
          entity_id: switch.wc_switch_1_green_3
    - conditions:
      - condition: template
        value_template: "{{ is_state('switch.wc_mirror', 'on') }}"
      sequence:
      - service: switch.turn_off
        data: {}
        target:
          entity_id: switch.wc_mirror
      - service: switch.turn_off
        data: {}
        target:
          entity_id: switch.wc_switch_1_green_2
      - service: switch.turn_off
        data: {}
        target:
          entity_id: switch.wc_switch_1_green_3
  mode: single
- id: 'wc_switch_1_down_2'
  alias: WC Switch 1 Down 2
  description: 'WC Switch 1 Down 2'
  trigger:
  - platform: webhook
    webhook_id: '0x0101004a'
  - platform: webhook
    webhook_id: '0x0101001a'
  condition:
  - condition: template
    value_template: "{{ trigger.json.event_id == '29' and trigger.json.device_state == '1' }}"
  action:
  - choose:
    - conditions:
      - condition: template
        value_template: "{{ is_state('switch.wc_backlight', 'off') }}"
      sequence:
      - service: switch.turn_on
        data: {}
        target:
          entity_id: switch.wc_backlight
      - service: switch.turn_on
        data: {}
        target:
          entity_id: switch.wc_switch_1_red_2
      - service: switch.turn_on
        data: {}
        target:
          entity_id: switch.wc_switch_1_red_3
    - conditions:
      - condition: template
        value_template: "{{ is_state('switch.wc_backlight', 'on') }}"
      sequence:
      - service: switch.turn_off
        data: {}
        target:
          entity_id: switch.wc_backlight
      - service: switch.turn_off
        data: {}
        target:
          entity_id: switch.wc_switch_1_red_2
      - service: switch.turn_off
        data: {}
        target:
          entity_id: switch.wc_switch_1_red_3
  mode: single


    # 'Up1': '0x01010047',
    # 'Down1': '0x01010048',
    # 'Up2': '0x01010049',
    # 'Down2': '0x0101004a',
    # 'Up3': '0x01010019',
    # 'Down3': '0x0101001a',
    # 'Green1': '0x01020053',
    # 'Red1': '0x01020054',
    # 'Green2': '0x01020055',
    # 'Red2': '0x01020056',
    # 'Green3': '0x0102001d',
    # 'Red3': ' 0x0102001e',
    # 'Humidity': '0x01050006',
    # 'Therm': '0x01050008',
    # 'Therm_Inter': '0x01050007',