# WC Floor Heater
- platform: generic_thermostat
  unique_id: wc_floor_heater
  name: WC Floor Heater
  heater: switch.wc_floor_heater_tmp
  ac_mode: false
  min_temp: 18
  max_temp: 25
  hot_tolerance: 0.5
  cold_tolerance: 0.5
  target_temp: 24
  away_temp: 2
  target_sensor: sensor.wc_temperature
