# Hall Floor Heater
- platform: generic_thermostat
  unique_id: hall_floor_heater
  name: Hall Floor Heater
  heater: switch.hall_floor_heater_tmp
  ac_mode: false
  min_temp: 23
  max_temp: 25
  hot_tolerance: 0.5
  cold_tolerance: 0.5
  target_temp: 24
  away_temp: 23
  comfort_temp: 24
  target_sensor: sensor.hall_temperature