- platform: generic_thermostat
  unique_id: hall_floor_heater
  name: Hall Floor Heater
  heater: switch.cabinet_chandelier_tmp
  ac_mode: false
  min_temp: 18
  max_temp: 25
  hot_tolerance: 0.5
  cold_tolerance: 0.5
  target_temp: 20
  away_temp: 2
  target_sensor: sensor.hall_temperature
