# Hall Floor Heater
- platform: generic_thermostat
  unique_id: hall_floor_heater
  name: Hall Floor Heater
  heater: switch.hall_floor_heater_tmp
  ac_mode: false
  min_temp: 10
  max_temp: 30
  hot_tolerance: 0.5
  cold_tolerance: 0.5
  target_temp: 22
  away_temp: 2
  target_sensor: sensor.hall_temperature