
- platform: ELKO_telnet
  switches:
    hall_floor_heater: &settings
      name: Hall Floor Heater
      resource: "192.168.88.246"
      device_id: "0x0102003B"
      port: 1111
      command_on: "1"
      command_off: "0"
      value_template: >-
        {% if value == '1' %}
          True
        {% else %}
          False
        {% endif %}
      timeout: 0.1
