
- platform: ELKO_telnet
  switches:
    hall_floor_heater: &settings
      name: Hall Floor Heater
      resource: "192.168.88.246"
      device_id: "0x0102003B"
      port: 1111
      command_on: "1"
      command_off: "0"
      value_template: >-
        {% if value == '1' %}
          True
        {% else %}
          False
        {% endif %}
      timeout: 0.1

- platform: template
  switches:
    hall_floor_heater_tmp:
      value_template: "{{ is_state('switch.hall_floor_heater', 'on') }}"
      turn_on:
        service: switch.turn_on
        target:
          entity_id: switch.hall_floor_heater
      turn_off:
        service: switch.turn_off
        target:
          entity_id: switch.hall_floor_heater
      icon_template: >-
        {% if is_state('switch.hall_floor_heater', 'on') %}
          mdi:radiator
        {% else %}
          mdi:radiator-disabled
        {% endif %}